main: uk.codingbadgers.plugincore.PluginCore

name: ${project.artifactId}
version: ${project.version}
description: Core plugin for the CodingBadgers module system.
authors: [n3wton, thefish97]
website: https://github.com/CodingBadgers/PluginCore
depends: []
softdepend: []
api-version: 1.14

commands:
  plugincore:
    description: Main command for the plugin
    usage: /<command>
    aliases: pc